#!/bin/bash
make clean
make mrproper
rm arch/arm/boot/zImage-dtb
rm arch/arm/boot/zImage
rm -f repack_zip/system/lib/modules/*
rm -f drivers/platform/msm/ipa/ipa_common
rm arch/arm/boot/compressed/ashldi3.S
rm arch/arm/boot/compressed/hyp-stub.S
rm arch/arm/boot/compressed/lib1funcs.S
rm arch/arm/boot/compressed/piggy.gzip
rm arch/arm/boot/compressed/vmlinux
rm arch/arm/boot/compressed/vmlinux.lds
rm arch/arm/boot/dts/msm8952-sharp-pa35-mtp.dtb
rm arch/arm/kernel/vmlinux.lds
rm arch/arm/boot/Image
rm repack_zip/emp/zImage
rm kernel.zip
echo "done"
