#!/bin/bash
make clean
make mrproper
rm arch/arm/boot/zImage-dtb
rm arch/arm/boot/zImage
rm -f repack_zip/system/lib/modules/*.ko
rm -f drivers/platform/msm/ipa/ipa_common
rm arch/arm/boot/Image
rm repack_zip/emp/zImage
echo "done"
