#!/bin/bash

VER=$1
SUB=$2

rm -f repack_zip/emp/zImage
rm -f repack_zip/system/lib/modules/*.ko

if [ ! -d repack_zip/system ]; then
	mkdir repack_zip/system
	mkdir repack_zip/system/lib
	mkdir repack_zip/system/lib/modules
fi

mv arch/arm/boot/zImage-dtb repack_zip/emp/zImage
find -name "*.ko" -exec mv {} repack_zip/system/lib/modules \;

cd repack_zip
zip -r kernel.zip *
mv kernel.zip ../
cd ..
echo "--------------------------------------------------"
echo "-              Repack      Completed             -"
echo "--------------------------------------------------"
echo "-              kernel  by rote66                 -"
echo "--------------------------------------------------"
echo "-Cuttting Edge Aftermarket   Wear  Technology-----"
echo "--------------------------------------------------"
